# Generated by Django 3.2.4 on 2021-06-24 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0004_remove_amazon_admin_state'),
    ]

    operations = [
        migrations.AlterField(
            model_name='amazon_admin',
            name='password',
            field=models.CharField(blank=True, max_length=300, null=True, unique=True),
        ),
    ]
