# Generated by Django 3.2.4 on 2021-06-24 10:57

from django.db import migrations, models
import django.db.models.deletion
import localflavor.in_.models


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0006_alter_amazon_admin_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='amazon_admin',
            name='state',
            field=localflavor.in_.models.INStateField(blank=True, max_length=2, null=True),
        ),
        migrations.CreateModel(
            name='amazon_admin_notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField()),
                ('seen', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
                ('amazon_admin', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Admin.amazon_admin')),
            ],
        ),
    ]
